### ISSUE TITLE
noop ?

### ISSUE THREAD

**Issue by setop** [r0f1/adventofcode2020#2]
https://github.com/r0f1/adventofcode2020/blob/ddc261c6cfb8185fd6ec38c7ae8ddd185b43cbb1/day08/main.py#L19

**Comment by r0f1** [comment]
Hi, can you maybe elaborate a little? Do you have any suggestions on how to make that code more efficient or elegant? Let's discuss :)

**Comment by setop** [comment]
The problem states "nop", one o, not two.
All instructions are on three characters
So i'm wondering how this code could be a solution.

**Comment by r0f1** [comment]
Ah, I did not realize. In line 19, the line that you are referencing, this mistake does not matter, since the instruction is a `pass` anyways. One could even delete the entire line and the program would be semantically the same. 
In lines 26 and 28, I again write noop with two "o"s. I cannot tell with absolute certainty why this mistake does not matter, but I hypothezise that my input sequence was in a way that replacing jmps yielded the desired solution, and not replacing nops.

**Comment by setop** [comment]
Thanks for your gentle reply and sorry for the intrusion. I'm browsing some AoC repo to compare to the solutions I found. Always educational.

**Comment by r0f1** [comment]
You're welcome. No intrusion at all. I love talking about this stuff :) Since I think this is resolved, I am closing this issue. Feel free to open issues again if you have questions.
